globalThis.OFO_COPILOT_DOMAINS = {
  ownedHosts: [
    "openfrontier.one",
    "freeappstore.online",
    "proappstore.online",
    "freegamestore.online",
    "progamestore.online",
    "freewebstore.online",
    "prowebstore.online",
    "freeagentstore.online",
    "proagentstore.online",
    "freeideastore.serge-the-dev.workers.dev",
    "proideastore.serge-the-dev.workers.dev"
  ],
  pagesHosts: [
    "openfrontier.pages.dev",
    "openfrontier-docs.pages.dev",
    "freequantumstore.pages.dev",
    "freecryptostore.pages.dev",
    "freechipstore.pages.dev",
    "freespacestore.pages.dev",
    "freebiostore.pages.dev",
    "freedesignstore.pages.dev",
    "freemarketingstore.pages.dev",
    "freecodestore.pages.dev",
    "freemusicstore.pages.dev",
    "freewritingstore.pages.dev",
    "freebookstore.pages.dev",
    "freefinancestore.pages.dev",
    "freedatastore.pages.dev",
    "freepeerstore.pages.dev"
  ],
  storeProfiles: {
    "openfrontier.one": { label: "Open Frontier One", category: "umbrella", community: "OFO platform" },
    "freeappstore.online": { label: "FreeAppStore", category: "apps", community: "app builders" },
    "proappstore.online": { label: "ProAppStore", category: "apps", community: "pro app builders" },
    "freegamestore.online": { label: "FreeGameStore", category: "games", community: "game builders" },
    "progamestore.online": { label: "ProGameStore", category: "games", community: "pro game builders" },
    "freewebstore.online": { label: "FreeWebStore", category: "websites", community: "website creators" },
    "prowebstore.online": { label: "ProWebStore", category: "websites", community: "CMS builders" },
    "freeagentstore.online": { label: "FreeAgentStore", category: "agents", community: "agent builders" },
    "proagentstore.online": { label: "ProAgentStore", category: "agents", community: "pro agent builders" },
    "freeideastore.serge-the-dev.workers.dev": { label: "FreeIdeaStore", category: "ideas", community: "idea contributors" },
    "proideastore.serge-the-dev.workers.dev": { label: "ProIdeaStore", category: "ideas", community: "idea diligence contributors" },
    "freequantumstore.pages.dev": { label: "FreeQuantumStore", category: "quantum", community: "quantum learners" },
    "freecryptostore.pages.dev": { label: "FreeCryptoStore", category: "crypto", community: "crypto systems learners" },
    "freechipstore.pages.dev": { label: "FreeChipStore", category: "chip design", community: "hardware learners" },
    "freespacestore.pages.dev": { label: "FreeSpaceStore", category: "space", community: "space systems learners" },
    "freebiostore.pages.dev": { label: "FreeBioStore", category: "biology", community: "biology learners" },
    "freedesignstore.pages.dev": { label: "FreeDesignStore", category: "design", community: "design contributors" },
    "freemarketingstore.pages.dev": { label: "FreeMarketingStore", category: "marketing", community: "marketing practitioners" },
    "freecodestore.pages.dev": { label: "FreeCodeStore", category: "code", community: "developers" },
    "freemusicstore.pages.dev": { label: "FreeMusicStore", category: "music", community: "music creators" },
    "freewritingstore.pages.dev": { label: "FreeWritingStore", category: "writing", community: "writers" },
    "freebookstore.pages.dev": { label: "FreeBookStore", category: "books", community: "readers and publishers" },
    "freefinancestore.pages.dev": { label: "FreeFinanceStore", category: "finance", community: "finance tool users" },
    "freedatastore.pages.dev": { label: "FreeDataStore", category: "data", community: "data practitioners" },
    "freepeerstore.pages.dev": { label: "FreePeerStore", category: "peer-to-peer", community: "distributed systems builders" }
  }
};
